apiVersion: v1
kind: Service
metadata:
  name: cloudops-backend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: cloudops-backend
  ports:
    - port: 5000
      targetPort: 5000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: cloudops-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: cloudops-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
