apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: default

resources:
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cloudops-backend
    spec:
      replicas: 1
